adjectives = [
    'adventurous', 'ambitious', 'amusing', 'ancient', 'attractive', 'awesome', 'beautiful', 'bold', 'brave', 'bright', 
    'brilliant', 'calm', 'charming', 'cheerful', 'clever', 'confident', 'cool', 'courageous', 'cunning', 'curious', 
    'daring', 'delightful', 'determined', 'diligent', 'eager', 'elegant', 'energetic', 'enthusiastic', 'experienced', 
    'famous', 'fearless', 'fierce', 'friendly', 'funny', 'generous', 'gentle', 'gifted', 'gigantic', 'gleaming', 
    'glorious', 'graceful', 'handsome', 'happy', 'helpful', 'hilarious', 'honest', 'humble', 'humorous', 'imaginative', 
    'intelligent', 'jolly', 'joyful', 'kind', 'lively', 'lovable', 'loyal', 'magnificent', 'majestic', 'mighty', 
    'mischievous', 'modest', 'mystic', 'noble', 'obedient', 'outgoing', 'patient', 'peaceful', 'perfect', 'persistent', 
    'playful', 'polite', 'powerful', 'pretty', 'proud', 'quiet', 'radiant', 'reliable', 'resilient', 'resourceful', 
    'respectful', 'romantic', 'sensitive', 'sincere', 'sleepy', 'smart', 'smiling', 'sparkling', 'splendid', 'strong', 
    'successful', 'sunny', 'talented', 'thoughtful', 'tireless', 'trustworthy', 'valiant', 'vibrant', 'vigilant', 'warm', 
    'whimsical', 'wise', 'witty', 'wonderful', 'zealous', 'accomplished', 'adaptable', 'affectionate', 'agreeable', 
    'alert', 'amazed', 'amazing', 'amorous', 'animated', 'ardent', 'artistic', 'athletic', 'attentive', 'authentic', 
    'aware', 'balanced', 'benevolent', 'blissful', 'blithe', 'bouncy', 'breezy', 'buoyant', 'capable', 'captivating', 
    'carefree', 'charismatic', 'chivalrous', 'colorful', 'compassionate', 'concise', 'considerate', 'consistent', 
    'cooperative', 'creative', 'credible', 'dapper', 'debonair', 'decisive', 'dedicated', 'dependable', 'desirable', 
    'determined', 'devoted', 'diligent', 'discreet', 'dynamic', 'earnest', 'ecstatic', 'efficient', 'effortless', 
    'elevated', 'empathetic', 'empowered', 'enchanting', 'encouraging', 'enlightened', 'exceptional', 'exhilarated', 
    'extraordinary', 'exuberant', 'fabulous', 'fair', 'faithful', 'fearless', 'flourishing', 'focused', 'forgiving', 
    'fortunate', 'free', 'fulfilled', 'genuine', 'giddy', 'gracious', 'gregarious', 'harmonious', 'hearty', 'heavenly', 
    'hopeful', 'illustrious', 'impeccable', 'incredible', 'inspired', 'invincible', 'irresistible', 'jovial', 'jubilant', 
    'keen', 'laudable', 'lighthearted', 'lucid', 'marvelous', 'mature', 'mellow', 'meritorious', 'meticulous', 
    'mindful', 'motivated', 'nurturing', 'optimistic', 'organized', 'passionate', 'peaceful', 'perceptive', 
    'perseverant', 'philosophical', 'playful', 'poised', 'positive', 'precise', 'pristine', 'proactive', 'productive', 
    'profound', 'progressive', 'prolific', 'prosperous', 'prudent', 'punctual', 'radiant', 'rational', 'realistic', 
    'reflective', 'resilient', 'resolute', 'resourceful', 'respectful', 'reverent', 'sagacious', 'sanguine', 'satisfied', 
    'sensible', 'serene', 'skillful', 'sophisticated', 'spirited', 'spontaneous', 'steady', 'strategic', 'studious', 
    'successful', 'supportive', 'sympathetic', 'tenacious', 'thoughtful', 'thrifty', 'tolerant', 'trusting', 
    'trustworthy', 'truthful', 'unassuming', 'understanding', 'upbeat', 'valiant', 'versatile', 'vibrant', 'vigilant', 
    'virtuous', 'vivacious', 'warmhearted', 'wise', 'witty', 'worthy', 'youthful', 'zealous'
]

nouns = [
    'acorn', 'airplane', 'alligator', 'ant', 'apple', 'artichoke', 'asteroid', 'axe', 'badger', 'banana', 
    'barn', 'basket', 'bathtub', 'beach', 'bear', 'beaver', 'bee', 'bird', 'bison', 'blueberry', 'book', 
    'boulder', 'bowl', 'brush', 'butterfly', 'camel', 'candle', 'canoe', 'carrot', 'cat', 'caterpillar', 
    'chair', 'cherry', 'chestnut', 'chipmunk', 'coconut', 'comet', 'crayon', 'crown', 'deer', 'desk', 
    'diamond', 'dinosaur', 'dog', 'dolphin', 'donkey', 'dragon', 'duck', 'eagle', 'egg', 'elephant', 
    'feather', 'fern', 'firefly', 'fish', 'flamingo', 'flower', 'fox', 'frog', 'giraffe', 'glacier', 
    'grape', 'grasshopper', 'hamster', 'harp', 'hat', 'hedge', 'helicopter', 'honeybee', 'horse', 
    'hummingbird', 'igloo', 'jellyfish', 'kangaroo', 'kite', 'koala', 'lemon', 'leopard', 'lighthouse', 
    'lion', 'lobster', 'mango', 'maple', 'meadow', 'meteor', 'mirror', 'monkey', 'moon', 'moose', 
    'mountain', 'mushroom', 'oak', 'ocean', 'orange', 'otter', 'owl', 'panda', 'peach', 'pear', 
    'penguin', 'pineapple', 'rabbit', 'raccoon', 'rainbow', 'raspberry', 'river', 'rose', 'sailboat', 
    'salmon', 'sand', 'seahorse', 'seashell', 'shark', 'snowflake', 'spider', 'squirrel', 'star', 
    'strawberry', 'sunflower', 'swan', 'tiger', 'tomato', 'tornado', 'turtle', 'umbrella', 'volcano', 
    'waterfall', 'watermelon', 'whale', 'willow', 'zebra', 'accordian', 'albatross', 'almond', 'anchovy', 
    'antelope', 'apricot', 'arch', 'armor', 'arrow', 'avocado', 'backpack', 'badge', 'bagel', 'balloon', 
    'balcony', 'ball', 'barrel', 'basin', 'beaker', 'bean', 'beetle', 'bell', 'belt', 'berry', 
    'bicycle', 'blender', 'blimp', 'blossom', 'board', 'boat', 'bonnet', 'boot', 'bottle', 'bow', 
    'box', 'bracelet', 'brick', 'bridge', 'brush', 'bucket', 'bulb', 'bush', 'button', 'cactus', 
    'cake', 'calculator', 'calendar', 'camera', 'candy', 'cap', 'cape', 'car', 'castle', 'cave', 
    'ceiling', 'chain', 'chalk', 'chimney', 'church', 'clay', 'cliff', 'cloud', 'clover', 'coast', 
    'coil', 'collar', 'compass', 'cookie', 'coral', 'cord', 'cork', 'corn', 'corset', 'cotton', 
    'crab', 'crane', 'crate', 'crescent', 'crow', 'cube', 'cup', 'cushion', 'dam', 'dome', 
    'donut', 'dove', 'dragonfly', 'dune', 'easel', 'echo', 'eel', 'emerald', 'emu', 'eraser', 
    'eyebrow', 'fable', 'fairy', 'falcon', 'fan', 'fang', 'faucet', 'fig', 'finch', 'flag', 
    'flute', 'forest', 'fork', 'fort', 'fossil', 'fountain', 'frisbee', 'furnace', 'galaxy', 'gazebo', 
    'gem', 'geode', 'geyser', 'goblet', 'goose', 'grill', 'gull', 'gust', 'gyroscope', 'hammock', 
    'handle', 'hatch', 'hive', 'hook', 'horn', 'house', 'hutch', 'iceberg', 'iguanodon', 'incense', 
    'ink', 'iron', 'ivory', 'jacket', 'jar', 'jaw', 'jet', 'jug', 'kayak', 'kettle', 
    'key', 'kiwi', 'knee', 'knob', 'knoll', 'knot', 'kraken', 'labyrinth', 'ladder', 'lamp', 
    'lantern', 'lasso', 'leaf', 'leg', 'lens', 'lever', 'lightning', 'lily', 'lime', 'loch', 
    'luggage', 'lunar', 'lyric', 'macaroon', 'mammoth', 'mantis', 'map', 'marble', 'mask', 'mast', 
    'maze', 'meadowlark', 'melon', 'mesa', 'meteorite', 'minnow', 'mixer', 'moccasin', 'molar', 'mosquito', 
    'moss', 'muffin', 'nail', 'napkin', 'nectar', 'nest', 'ninja', 'noodle', 'novel', 'nymph', 
    'oasis', 'obelisk', 'octagon', 'onion', 'orchid', 'ornament', 'ostrich', 'padlock', 'pancake', 'panther', 
    'parachute', 'parrot', 'pebble', 'peg', 'pelican', 'pepper', 'perch', 'pickle', 'pier', 'pig', 
    'pigeon', 'pine', 'pipe', 'plank', 'plum', 'pomegranate', 'poppy', 'porcupine', 'portal', 'potato', 
    'pouch', 'prairie', 'prism', 'pumpkin', 'puzzle', 'quail', 'quartz', 'quill', 'quilt', 'quokka', 
    'radish', 'rail', 'rake', 'reed', 'reef', 'reindeer', 'relic', 'rhino', 'ring', 'root', 
    'rope', 'saber', 'saddle', 'sage', 'scarf', 'scepter', 'schooner', 'scorpion', 'scroll', 'scythe', 
    'seed', 'serpent', 'shingle', 'silk', 'slate', 'sloth', 'slug', 'snail', 'snipe', 'snowman', 
    'sock', 'spectacles', 'sphere', 'spindle', 'sponge', 'spring', 'squid', 'staff', 'stair', 'stalk', 
    'stamp', 'stem', 'stool', 'strata', 'sugar', 'surfer', 'sword', 'sycamore', 'tambourine', 'tapir', 
    'teacup', 'teapot', 'thicket', 'thread', 'thrush', 'thunder', 'thyme', 'tome', 'topaz', 'totem', 
    'trampoline', 'trap', 'trident', 'trough', 'trunk', 'tulip', 'turkey', 'twig', 'unicorn', 'urn', 
    'utensil', 'utopia', 'vase', 'veil', 'vine', 'violin', 'vulture', 'waffle', 'walnut', 'warthog', 
    'watch', 'wattle', 'web', 'wheel', 'whip', 'wombat', 'wren', 'xylophone', 'yarn', 'yeti', 
    'yoke', 'zephyr', 'zigzag', 'zipper'
]
