# Generated by Django 4.2.7 on 2024-04-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encryption_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passwordsJson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
