# Generated by Django 4.2.7 on 2024-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encryption_App', '0002_userprofile_passwordsjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='passwordsJson',
            field=models.TextField(blank=True, null=True),
        ),
    ]
