# Generated by Django 4.2.7 on 2024-05-19 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Encryption_App', '0004_userprofile_nonce_userprofile_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('nonce', models.TextField(blank=True, null=True)),
                ('ciphertext', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
