# Generated by Django 4.2.7 on 2024-05-19 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Encryption_App', '0005_websitepassword_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitepassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
