# Generated by Django 4.2.7 on 2024-05-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encryption_App', '0006_alter_websitepassword_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitepassword',
            options={'managed': False},
        ),
    ]
