# Generated by Django 3.2.25 on 2024-05-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encryption_App', '0007_alter_websitepassword_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitepassword',
            options={},
        ),
    ]
