# Generated by Django 4.2.13 on 2024-05-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encryption_App', '0009_auto_20240520_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepassword',
            name='hashed_website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
