# Generated by Django 4.2.7 on 2024-06-05 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Encryption_App', '0014_alter_websitepassword_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_message', models.TextField(blank=True, null=True)),
                ('message', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('tag', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('nonce', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('ciphertext', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
